import {
  ArrowRight,
  ArrowUpRight,
  Bell,
  Briefcase,
  Building2,
  CalendarCheck,
  ChevronDown,
  ChevronRight,
  Check,
  CircleCheck,
  ChartColumn,
  Clock,
  Cloud,
  Code,
  Compass,
  Facebook,
  Github,
  Globe,
  Headset,
  Instagram,
  Layers,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  Palette,
  Phone,
  Quote,
  Search,
  Server,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Ticket,
  Truck,
  Twitter,
  Users,
  Wallet,
  Workflow,
  X,
  Zap,
} from 'lucide-angular';
import { IconName } from './icon.types';

export const LUCIDE_ICON_SET = {
  ArrowRight,
  ArrowUpRight,
  Bell,
  Briefcase,
  Building2,
  CalendarCheck,
  ChevronDown,
  ChevronRight,
  Check,
  CircleCheck,
  ChartColumn,
  Clock,
  Cloud,
  Code,
  Compass,
  Facebook,
  Github,
  Globe,
  Headset,
  Instagram,
  Layers,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  Palette,
  Phone,
  Quote,
  Search,
  Server,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Ticket,
  Truck,
  Twitter,
  Users,
  Wallet,
  Workflow,
  X,
  Zap,
};

export const ICON_MAP: Record<IconName, keyof typeof LUCIDE_ICON_SET> = {
  code: 'Code',
  bell: 'Bell',
  briefcase: 'Briefcase',
  'calendar-check': 'CalendarCheck',
  server: 'Server',
  workflow: 'Workflow',
  mobile: 'Smartphone',
  cloud: 'Cloud',
  swatch: 'Palette',
  chart: 'ChartColumn',
  support: 'Headset',
  check: 'Check',
  'check-circle': 'CircleCheck',
  'arrow-right': 'ArrowRight',
  'arrow-up-right': 'ArrowUpRight',
  menu: 'Menu',
  close: 'X',
  'chevron-down': 'ChevronDown',
  'chevron-right': 'ChevronRight',
  star: 'Star',
  quote: 'Quote',
  'map-pin': 'MapPin',
  phone: 'Phone',
  mail: 'Mail',
  linkedin: 'Linkedin',
  twitter: 'Twitter',
  x: 'X',
  github: 'Github',
  facebook: 'Facebook',
  instagram: 'Instagram',
  shield: 'Shield',
  bolt: 'Zap',
  users: 'Users',
  target: 'Target',
  sparkles: 'Sparkles',
  globe: 'Globe',
  ticket: 'Ticket',
  truck: 'Truck',
  wallet: 'Wallet',
  building: 'Building2',
  compass: 'Compass',
  layers: 'Layers',
  clock: 'Clock',
  search: 'Search',
};
